# Generated by Django 6.0.5 on 2026-05-30 00:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("coffees", models.PositiveIntegerField(default=0)),
                ("useless_meetings", models.PositiveIntegerField(default=0)),
                ("traffic_minutes", models.PositiveIntegerField(default=0)),
                ("stress_level", models.PositiveSmallIntegerField(default=5)),
                ("bathroom_revenue_cents", models.PositiveIntegerField(default=0)),
                ("buzzwords_endured", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("burny_score", models.PositiveSmallIntegerField(default=0)),
                ("burny_insight", models.CharField(blank=True, max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "date"), name="unique_checkin_per_day"
                    )
                ],
            },
        ),
    ]
