# Generated by Django 6.0.5 on 2026-05-30 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_follow_skillendorsement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desabafo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("funcional", "Funcional demais para meu próprio bem"),
                            ("alerta", "Em alerta laranja"),
                            ("critico", "Nível crítico"),
                            ("colapso", "Colapso iminente 🔥"),
                        ],
                        default="funcional",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desabafos",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("choro", "😭"),
                            ("morto", "💀"),
                            ("cafe", "☕"),
                            ("fogo", "🔥"),
                            ("abraco", "🤝"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "desabafo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reacoes",
                        to="social.desabafo",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reacoes",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("profile", "desabafo")},
            },
        ),
    ]
