# Generated by Django 6.0.5 on 2026-05-30 00:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=64)),
                ("avatar_emoji", models.CharField(default="🔥", max_length=8)),
                ("region", models.CharField(default="Brasil", max_length=64)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("dev", "Desenvolvimento"),
                            ("design", "Design"),
                            ("product", "Produto"),
                            ("ops", "Operacoes"),
                            ("data", "Dados"),
                            ("qa", "QA"),
                            ("management", "Gestao"),
                            ("sales", "Vendas"),
                            ("marketing", "Marketing"),
                            ("other", "Outros"),
                        ],
                        default="dev",
                        max_length=32,
                    ),
                ),
                (
                    "access_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
