# Generated by Django 6.0.5 on 2026-05-30 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to="users.profile",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers_set",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="SkillEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("reunioes_survival", "Sobrevivência em Reuniões de 2h"),
                            ("cafe_pro", "Consumo Avançado de Café"),
                            ("tudo_bem", "Arte de Fingir que Está Tudo Bem"),
                            ("crise_1759", "Gestão de Crises às 17h59"),
                            ("banheiro", "Otimização de Tempo no Banheiro"),
                            (
                                "email_urgente",
                                "Leitura de E-mail como se Fosse Urgente",
                            ),
                            ("procrastinacao", "Procrastinação Estratégica"),
                            ("pos_daily", "Resiliência Pós-Daily"),
                            (
                                "reuniao_email",
                                "Especialista em Reuniões que Poderiam ser E-mail",
                            ),
                            ("git_blame", "Mestre do Git Blame Criativo"),
                            ("deadline_ninja", "Ninja de Deadlines de última Hora"),
                            ("slack_offline", "Expert em Parecer Offline no Slack"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endorser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_given",
                        to="users.profile",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_received",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("endorser", "profile", "skill")},
            },
        ),
    ]
