# Generated by Django 6.0.5 on 2026-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adiciona monthly_salary_cents ao Profile.

    Reescrita para remover operações de constraint que falhavam em produção
    (RemoveConstraint + AlterUniqueTogether desnecessários para esta feature).
    """

    dependencies = [
        ("users", "0004_conviteamigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="monthly_salary_cents",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
