# Generated by Django 6.0.5 on 2026-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_conviteamigo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conviteamigo",
            name="unique_convite_por_tipo",
        ),
        migrations.AddField(
            model_name="profile",
            name="monthly_salary_cents",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="conviteamigo",
            unique_together={("remetente", "tipo_relacao")},
        ),
    ]
