# Generated by Django 6.0.5 on 2026-05-31 00:29

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor):
    """Remove unique_convite_por_tipo de forma idempotente (PostgreSQL e SQLite)."""
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            """
            DO $$ BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'unique_convite_por_tipo'
                ) THEN
                    ALTER TABLE users_conviteamigo DROP CONSTRAINT unique_convite_por_tipo;
                END IF;
            END $$;
            """
        )
    # SQLite: constraints can't be dropped individually; no-op is safe.


def add_unique_together_if_missing(apps, schema_editor):
    """Adiciona unique_together em conviteamigo de forma idempotente."""
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            """
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes
                    WHERE indexname LIKE '%%conviteamigo%%remetente%%tipo_relacao%%'
                       OR indexname LIKE '%%conviteamigo%%tipo_relacao%%remetente%%'
                ) THEN
                    CREATE UNIQUE INDEX users_conviteamigo_remetente_id_tipo_relacao_uniq
                    ON users_conviteamigo (remetente_id, tipo_relacao);
                END IF;
            END $$;
            """
        )
    elif vendor == "sqlite":
        try:
            schema_editor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS "
                "users_conviteamigo_remetente_id_tipo_relacao_eab78d0d_uniq "
                "ON users_conviteamigo (remetente_id, tipo_relacao)"
            )
        except Exception:
            pass  # Index already exists


class Migration(migrations.Migration):
    """Reconcilia constraint unique_convite_por_tipo com unique_together do model.

    Usa RunPython + SeparateDatabaseAndState para ser idempotente em produção:
    o constraint pode ou não existir dependendo do estado anterior.
    """

    dependencies = [
        ("users", "0005_monthly_salary"),
    ]

    operations = [
        # Atualiza o estado do Django sem re-executar (já foi feito pelo 0004/0005).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(remove_constraint_if_exists, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="conviteamigo",
                    name="unique_convite_por_tipo",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_unique_together_if_missing, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="conviteamigo",
                    unique_together={("remetente", "tipo_relacao")},
                ),
            ],
        ),
    ]
