# Generated by Django 6.0.5 on 2026-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_conviteamigo_unique_convite_por_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conviteamigo",
            name="tipo_relacao",
            field=models.CharField(
                choices=[
                    ("amigo", "🫂 Amigo"),
                    ("colega_trabalho", "💼 Colega de trabalho"),
                    ("conhecido_almoco", "🍽️ Conhecido do almoço"),
                    ("colega_profissao", "🤝 Colega de profissão"),
                    ("conhecido", "👋 Conhecido"),
                    ("chefe_querido", "😬 Meu chefe querido (a culpa é dele)"),
                ],
                max_length=20,
            ),
        ),
    ]
